

version: '3.8'
services:
  php-container:
    # image: php:8.3-apache
    container_name: booking_php
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - "8089:80"
    volumes:
      - ./website:/var/www/html
    networks:
      - booking-net

  mariadb-container:
    container_name: booking_mariadb
    image: mariadb
    restart: 'no'
    environment:
      MARIADB_DATABASE: booking
      MARIADB_USER: booking
      MARIADB_PASSWORD: booking
      MARIADB_ROOT_PASSWORD: booking
    ports:
      - "13306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - booking-net

networks:
  booking-net:
